import { translate as t } from '@/i18n/translate';
import { HELP_SECTIONS, type HelpSection } from '@/store/appStore';
import { GUIDE_STEPS } from './guideSteps';
import {
  DIAGRAM_TOPIC_IDS,
  FAQ_IDS,
  SHORTCUT_IDS,
  TROUBLESHOOTING_IDS,
  diagramTopicKey,
  faqKey,
  shortcutKey,
  stepKey,
  troubleshootingKey,
} from './helpContent';

/**
 * Where `docs/user-guide.md` finds the screenshots, relative to itself. They live beside the
 * renderer because the application bundles them; the document links to the same files rather than
 * keeping copies that could drift from what the Help screen shows.
 */
const SCREENSHOT_PATH = '../src/ui/src/help/screenshots';

/**
 * The whole of Help as one Markdown document, for `docs/user-guide.md`.
 *
 * Generated rather than written, so the guide someone reads on GitHub before installing and the one
 * the Help screen shows are the same words. `userGuideMarkdown.test.ts` fails when the committed file
 * is not what this produces; `npm run docs:guide` in `src/ui` rewrites it.
 *
 * The catalogue's prose is already Markdown — the subset `lib/markdown.ts` parses, which GitHub
 * renders the same way — so each string goes in as it is. Sections come in the order the Help screen
 * lists them.
 */
export function renderUserGuideMarkdown(): string {
  const blocks: string[] = [
    '<!--\n' +
      '  Generated from the `help` block of src/ui/src/i18n/en.ts by src/ui/src/help/userGuideMarkdown.ts.\n' +
      '  Do not edit this file: change the catalogue, then run `npm run docs:guide` in src/ui.\n' +
      '-->',
    `# ${t('help.document.title')}`,
    t('help.description'),
    t('help.document.inApp', { help: t('app.nav.help') }),
    HELP_SECTIONS.map((section) => `- [${t(`help.sections.${section}`)}](#${slug(t(`help.sections.${section}`))})`).join('\n'),
  ];

  for (const section of HELP_SECTIONS) {
    blocks.push(`## ${t(`help.sections.${section}`)}`, ...renderSection(section));
  }

  return `${blocks.join('\n\n')}\n`;
}

function renderSection(section: HelpSection): string[] {
  switch (section) {
    case 'guide':
      return [
        t('help.guide.intro'),
        ...GUIDE_STEPS.flatMap((step, index) => [
          `### ${index + 1}. ${t(stepKey(step.id, 'title'))}`,
          t(stepKey(step.id, 'body')),
          `![${t(stepKey(step.id, 'alt'))}](${SCREENSHOT_PATH}/${step.screenshot})`,
        ]),
      ];

    case 'about':
      return [
        t('help.about.body'),
        `### ${t('help.about.needsHeading')}`,
        t('help.about.needs'),
        `### ${t('help.about.neverHeading')}`,
        t('help.about.never'),
      ];

    case 'diagram':
      return [
        t('help.diagram.intro'),
        ...DIAGRAM_TOPIC_IDS.flatMap((id) => [
          `### ${t(diagramTopicKey(id, 'title'))}`,
          t(diagramTopicKey(id, 'body')),
        ]),
      ];

    case 'shortcuts':
      return [
        t('help.shortcuts.intro'),
        [
          `| ${t('help.shortcuts.keyColumn')} | ${t('help.shortcuts.actionColumn')} |`,
          '|---|---|',
          ...SHORTCUT_IDS.map(
            (id) => `| \`${t(shortcutKey(id, 'key'))}\` | ${t(shortcutKey(id, 'action'))} |`,
          ),
        ].join('\n'),
      ];

    case 'faq':
      return FAQ_IDS.flatMap((id) => [`### ${t(faqKey(id, 'question'))}`, t(faqKey(id, 'answer'))]);

    case 'troubleshooting':
      return TROUBLESHOOTING_IDS.flatMap((id) => [
        `### ${t(troubleshootingKey(id, 'title'))}`,
        t(troubleshootingKey(id, 'body')),
      ]);
  }
}

/** GitHub's heading anchor: lower case, punctuation dropped, spaces as hyphens. */
export function slug(heading: string): string {
  return heading
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s-]/gu, '')
    .trim()
    .replace(/\s/g, '-');
}
