<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DiffHacker.Git</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiffHacker.Contracts\DiffHacker.Contracts.csproj" />
    <ProjectReference Include="..\DiffHacker.Core\DiffHacker.Core.csproj" />
  </ItemGroup>

</Project>
